const sList = [
  { from: ':)', from2: ':-)', from3: '=)', to: '0x1F600' },
  { from: ':D', from2: ':-D', from3: '=D', to: '0x1F601' },
  { from: ':(', from2: ':-(', to: '0x1F62D' },
  { from: ';)', from2: ';-)', from3: '=)', to: '0x1F609' },
  // { from: ':/', from2: ':\\', from3: ':-/', from4: ':-\\', to: '0x1F615' },
  {
    from: ':s',
    from2: ':-S',
    from3: ':z',
    from4: ':-Z',
    from5: ':$',
    from6: ':-$',
    from7: ':S',
    to: '0x1F615',
  },
  {
    from: '>:(',
    from2: '>:[',
    from3: '>:-(',
    from4: '>:-[',
    from5: '>=(',
    from6: '>=[',
    from7: '>=-(',
    to: '0x1F621',
  },
  {
    from: ':")',
    from2: ':"]',
    from3: ':"D',
    from4: ':-")',
    from5: ':-"]',
    from6: ':-"D',
    from7: '=")',
    to: '0x1F605',
  },
  {
    from: ':p',
    from2: ':P',
    from3: ':-P',
    from4: ':-p',
    from5: '=p',
    from6: '=P',
    to: '0x1F60B',
  },
  {
    from: '8-)',
    from2: 'B-)',
    from3: 'B)',
    from4: '8)',
    to: '0x1F60E',
  },
  {
    from: ":,'(",
    from2: ":,'-(",
    from3: ';(',
    from4: ';-(',
    from5: ';=(',
    to: '0x1F622',
  },
  {
    from: 'x-)',
    from2: 'X-)',
    from3: 'X)',
    from4: 'x)',
    from5: 'x=)',
    from6: 'X=)',
    to: '0x1F602',
  },
  {
    from: ':o',
    from2: ':-o',
    from3: ':O',
    from4: ':-O',
    from5: ':=o',
    from6: ':=O',
    to: '0x1F627',
  },
  {
    from: ':@',
    from2: ':-@',
    from3: '=@',
    to: '0x1F92C',
  },
];
export default sList;
